<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $title ?></title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Mortal Fight</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="accueil.php">Accueil <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <span class="nav-item">
            <?php
                /*session_start();
                if(isset($_SESSION['user_ID'])){
                    echo " <a class='nav-link' href='Account.php?logout=1'>Bienvenue : ".$_SESSION['user_firstname']." | Déconnexion</a>";
                }else {
                 echo "<a class='nav-link' href='/'>Connexion</a>";
                }*/
            ?>
        </span>
    </div>
</nav>